=== leegbestand/eflint-jupyter/eflint/assets/schema.dtd
<!ELEMENT flint (specification,initials?,scenario?)>

  <!ELEMENT specification (ifact-frame|iduty-frame|iact-frame|alias)*>
    <!ATTLIST ifact-frame id CDATA #REQUIRED>
    <!ATTLIST iduty-frame id CDATA #REQUIRED>
    <!ATTLIST iact-frame  id CDATA #REQUIRED>
    <!ATTLIST alias      id CDATA #REQUIRED>

    <!ELEMENT ifact-frame (type-expr)>

    <!ELEMENT iduty-frame (holder,claimant,ifact-ref*,terminating_acts?,enforcing_acts?)>
      <!ELEMENT holder (ifact-ref)>
      <!ELEMENT claimant (ifact-ref)>
      <!ELEMENT terminating_acts (iact-type+)>
      <!ELEMENT enforcing_acts (iact-type+)>

    <!ELEMENT iact-frame (actor,subject,ifact-ref*,value-expr,iterminates?,icreates?)>
      <!ELEMENT actor (ifact-ref)>
      <!ELEMENT subject (ifact-ref)>
      <!ELEMENT iterminates (type+)>
      <!ELEMENT icreates (type+)>

    <!ELEMENT alias (value-expr)>

    <!ELEMENT type-expr ANY>
    <!ELEMENT type ANY>
    <!ELEMENT iact-type ANY>
    <!ELEMENT value-expr ANY>

    <!ELEMENT ifact-ref (type)>
    <!ELEMENT iduty-ref (type)>
    <!ELEMENT iact-ref  (type)>

  <!ELEMENT initials (decomposition*)>
    
    <!ELEMENT fact (string|int|fact)+>
      <!ATTLIST fact type CDATA #REQUIRED>
      <!ELEMENT string (#PCDATA)>
      <!ELEMENT int (#PCDATA)>

    <!ELEMENT act (fact,fact,fact*)> 
      <!ATTLIST act type CDATA #REQUIRED>

    <!ELEMENT duty (fact,fact,fact*)>
      <!ATTLIST duty type CDATA #REQUIRED>

  <!ELEMENT scenario (step*)> 
  
    <!ELEMENT step (decomposition*)>
      <!ELEMENT decomposition (type,binding*)>
      <!ELEMENT binding (type,element+)>
      <!ELEMENT element (string|int|fact|act|duty)>

=== leegbestand/eflint-jupyter/eflint/old-examples/permit_applications/permit_applications.xml
<?xml version="1.0"?>
<!DOCTYPE flint SYSTEM "../assets/schema.dtd">
<flint>
  <specification>
    <ifact-frame id="minister">
      <type-expr>["knapen" + "timmermans" + "benschop" + "patijn"]</type-expr>
    </ifact-frame>
    <iact-frame id="grant passport">
      <actor><ifact-ref><type>minister</type></ifact-ref></actor>
      <subject><ifact-ref><type>immigrant</type></ifact-ref></subject>
      <ifact-ref><type>passport</type></ifact-ref>
      <value-expr>true</value-expr>
      <iterminates>
        <type>application</type>
        <type>duty to consider</type>
      </iterminates>
      <icreates>
        <type>passport</type>
      </icreates>
    </iact-frame>
    <iact-frame id="deny application">
      <actor><ifact-ref><type>minister</type></ifact-ref></actor>
      <subject><ifact-ref><type>immigrant</type></ifact-ref></subject>
      <ifact-ref><type>application</type></ifact-ref>
      <value-expr>true</value-expr>
      <iterminates>
        <type>application</type>
        <type>duty to consider</type>
      </iterminates>
    </iact-frame>
    <iduty-frame id="duty to consider">
      <holder><ifact-ref><type>minister</type></ifact-ref></holder>
      <claimant><ifact-ref><type>immigrant</type></ifact-ref></claimant>
      <ifact-ref><type>application</type></ifact-ref>
      <terminating_acts>
        <iact-type>grant passport</iact-type>
        <iact-type>deny application</iact-type>
      </terminating_acts>
    </iduty-frame>

    <ifact-frame id="immigrant">
      <type-expr>["alice" + "bob" + "chloe" + "dharma" + "ellis"]</type-expr>
    </ifact-frame>
    <iact-frame id="apply for passport">
      <actor><ifact-ref><type>immigrant</type></ifact-ref></actor>
      <subject><ifact-ref><type>minister</type></ifact-ref></subject>
      <ifact-ref><type>application</type></ifact-ref>
      <value-expr>true</value-expr>
      <icreates>
        <type>application</type>
        <type>duty to consider</type>
      </icreates>
    </iact-frame>

    <ifact-frame id="passport">
      <type-expr>[immigrant]</type-expr>
    </ifact-frame>
    <ifact-frame id="application">
      <type-expr>[immigrant]</type-expr>
    </ifact-frame>
  </specification>

  <initials>
    <decomposition>
      <type>immigrant</type>
      <binding>
        <type>immigrant</type>
        <element><string>bob</string></element>
      </binding>
    </decomposition>
    <decomposition>
      <type>immigrant</type>
      <binding>
        <type>immigrant</type>
        <element><string>alice</string></element>
        </binding>
    </decomposition>
    <decomposition>
      <type>minister</type>
      <binding>
        <type>minister</type>
        <element><string>knapen</string></element>
      </binding>
    </decomposition>
    <decomposition>
      <type>apply for passport</type>
      <binding>
        <type>minister</type>
        <element><string>knapen</string></element>
      </binding>
    </decomposition>
  </initials>

 <scenario>
    <step>
      <decomposition>
        <type>apply for passport</type>
        <binding>
          <type>immigrant</type>
          <element><string>alice</string></element>
        </binding>
      </decomposition>
      <decomposition>
        <type>apply for passport</type>
        <binding>
          <type>immigrant</type>
          <element><string>bob</string></element>
        </binding>
      </decomposition>
    </step>
    <step>
      <decomposition>
        <type>grant passport</type>
      </decomposition>
    </step>
 </scenario> 
</flint>

=== leegbestand/eflint-jupyter/eflint/old-examples/parentship/guardianship.xml
<?xml version="1.0"?>
<!DOCTYPE flint SYSTEM "../assets/schema.dtd">
<flint>
  <specification>
    <ifact-frame id="person">
      <type-expr>["alice" + "bob" + "chloe" + "david" + "ellis" + "felix"]</type-expr>
    </ifact-frame>
    <ifact-frame id="father">
      <type-expr>[person1 * person2]</type-expr>
    </ifact-frame>
    <ifact-frame id="adoptive parent">
      <type-expr>[person1 * person2]</type-expr>
    </ifact-frame>
    <ifact-frame id="legal guardian">
      <type-expr>[adoptive parent + father]</type-expr>
    </ifact-frame>
    <iact-frame id="reward child">
      <actor><ifact-ref><type>person1</type></ifact-ref></actor>
      <subject><ifact-ref><type>person2</type></ifact-ref></subject>
      <value-expr>legal guardian</value-expr>
    </iact-frame> 
    <iact-frame id="call for help">
      <actor><ifact-ref><type>person1</type></ifact-ref></actor>
      <subject><ifact-ref><type>person2</type></ifact-ref></subject>
      <value-expr>legal guardian[person1=person2,person2=person1]</value-expr> 
    </iact-frame>
  </specification>
  <initials>
    <decomposition>
      <type>person</type> <!-- all persons are in the initial world -->
    </decomposition>
    <decomposition>
      <type>father</type>
      <binding>
        <type>person1</type>
        <element><string>bob</string></element>
      </binding>
      <binding>
        <type>person2</type>
        <element><string>chloe</string></element>
      </binding>
    </decomposition>
    <decomposition>
      <type>father</type>
      <binding>
        <type>person1</type>
        <element><string>bob</string></element>
      </binding>
      <binding>
        <type>person2</type>
        <element><string>david</string></element>
      </binding>
    </decomposition>
    <decomposition>
      <type>adoptive parent</type>
      <binding>
        <type>person1</type>
        <element><string>alice</string></element>
      </binding>
      <binding>
        <type>person2</type>
        <element><string>bob</string></element>
      </binding>
    </decomposition>
    <decomposition>
      <type>reward child</type>
      <binding>
        <type>person1</type>
        <element><string>bob</string></element>
      </binding>
    </decomposition> 
    <decomposition>
      <type>call for help</type>
    </decomposition>
  </initials>
</flint>

=== leegbestand/eflint-jupyter/eflint/old-examples/simple_renaming.xml
<?xml version="1.0"?>
<!DOCTYPE flint SYSTEM "../assets/schema.dtd">
<flint>
  <specification>
    <ifact-frame id="person">
      <type-expr>["john" + "alice"]</type-expr>
    </ifact-frame>   
    <ifact-frame id="application">
      <type-expr>[person]</type-expr>
    </ifact-frame>
    <iact-frame id="make application">
      <actor><ifact-ref><type>person</type></ifact-ref></actor>
      <subject><ifact-ref><type>person</type></ifact-ref></subject>
      <value-expr>true</value-expr>
      <icreates>
        <type>application[person=person]</type>
      </icreates>
    </iact-frame>
  </specification>
  <initials>
    <decomposition>
      <type>person</type>
    </decomposition>
    <decomposition>
      <type>make application</type>
    </decomposition>
  </initials>
</flint>
